In [2]:
import requests, json, time
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

In [3]:
movies = pd.read_csv("output5.csv", names = ['제목', '장르', '평점', '투표수', '사이트'])
print(movies.shape)
movies.head()

(1999, 5)


제목                    장르    평점   투표수  \
0     그린 북               ['드라마']  9.61  5937   
1     가버나움               ['드라마']  9.59  2882   
2      주전장             ['다큐멘터리']  9.56   853   
3  베일리 어게인  ['모험', '코미디', '드라마']  9.53  2147   
4      아일라         ['드라마', '전쟁']  9.48  1718   

                                                 사이트  
0  https://movie-phinf.pstatic.net//20190115_228/...  
1  https://movie-phinf.pstatic.net//20190109_149/...  
2  https://movie-phinf.pstatic.net//20190712_279/...  
3  https://movie-phinf.pstatic.net//20181031_264/...  
4  https://movie-phinf.pstatic.net//20180524_108/...

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
movies['장르'] = movies['장르'].apply(lambda x : x.replace("[", ''))
movies['장르'] = movies['장르'].apply(lambda x : x.replace("]", ''))
movies['장르'] = movies['장르'].apply(lambda x : x.replace(",", ''))
movies['장르'] = movies['장르'].apply(lambda x : x.replace("'", ''))

In [5]:
movies

제목                            장르    평점    투표수  \
0                      그린 북                           드라마  9.61   5937   
1                      가버나움                           드라마  9.59   2882   
2                       주전장                         다큐멘터리  9.56    853   
3                   베일리 어게인                    모험 코미디 드라마  9.53   2147   
4                       아일라                        드라마 전쟁  9.48   1718   
5                        원더                           드라마  9.46   2839   
6                        당갈                        드라마 액션  9.43   1979   
7                    쇼생크 탈출                           드라마  9.43  17677   
8                  보헤미안 랩소디                           드라마  9.42  39381   
9                   터미네이터 2                     SF 액션 스릴러  9.41   6961   
10                       덕구                           드라마  9.41   2482   
11                      알라딘       모험 가족 판타지 뮤지컬 멜로/애정/로맨스  9.40  26052   
12                      월-E  애니메이션 SF 가족 코미디 멜로/애정/로맨스 모험  9.40   9963   
13                 빽 투 더 퓨쳐                        SF 코미디  9.40   3043   
14                  나 홀로 집에                  모험 범죄 가족 코미디  9.39   4067   
15               라이언 일병 구하기                     전쟁 액션 드라마  9.39   4273   
16                 인생은 아름다워                       드라마 코미디  9.39  12057   
17                     매트릭스                         SF 액션  9.39   4667   
18                사운드 오브 뮤직             멜로/애정/로맨스 뮤지컬 드라마  9.39   4440   
19                  포레스트 검프                       드라마 코미디  9.39   7755   
20                       헬프                           드라마  9.39   3499   
21                   글래디에이터                        액션 드라마  9.38   4162   
22               어벤져스: 엔드게임                         액션 SF  9.38  68732   
23                   살인의 추억           범죄 미스터리 스릴러 코미디 드라마  9.38   6129   
24                 토이 스토리 3           애니메이션 모험 코미디 가족 판타지  9.38   7610   
25                   위대한 쇼맨                       드라마 뮤지컬  9.38  13734   
26             센과 치히로의 행방불명               애니메이션 판타지 모험 가족  9.36  12953   
27                      클래식                 멜로/애정/로맨스 드라마  9.36   8613   
28                죽은 시인의 사회                           드라마  9.36   7225   
29                 아이 캔 스피크                           드라마  9.36  14797   
...                     ...                           ...   ...    ...   
1969                   콜래트럴                    범죄 드라마 스릴러  8.03   1881   
1970                 베스트 키드                     액션 드라마 가족  8.03   1625   
1971                  머시니스트                       스릴러 드라마  8.03   1171   
1972               라스트 사무라이                  액션 모험 드라마 전쟁  8.03   1829   
1973                프리즈 프레임                    스릴러 범죄 드라마  8.03    611   
1974       나우 유 씨 미 : 마술사기단                   범죄 스릴러 미스터리  8.03   9570   
1975                     타워                           드라마  8.03  14215   
1976              레지던트 이블 2                  액션 공포 SF 스릴러  8.03   1648   
1977                해롤드와 쿠마                        코미디 모험  8.03    522   
1978                    엑스맨                         SF 액션  8.03    883   
1979              존 윅 - 리로드                     액션 범죄 스릴러  8.03   2310   
1980                 조작된 도시                         액션 범죄  8.03  16900   
1981             쿠보와 전설의 악기               애니메이션 모험 가족 판타지  8.03    325   
1982                 신의 한 수                         범죄 액션  8.03  11865   
1983   어디선가 누군가에 무슨 일이 생기..                 코미디 멜로/애정/로맨스  8.01    829   
1984            고양이를 빌려드립니다                       드라마 코미디  8.01    379   
1985                오션스 일레븐                        범죄 코미디  8.01    947   
1986                 슈렉 포에버           애니메이션 모험 코미디 가족 판타지  8.01   1461   
1987                 인천상륙작전                        전쟁 드라마  8.01  40339   
1988          미 마이셀프 앤드 아이린                           코미디  8.01    485   
1989                8명의 여인들               코미디 범죄 뮤지컬 미스터리  8.01    389   
1990       아스트로 보이 - 아톰의 귀환                애니메이션 SF 가족 액션  8.01    989   
1991     미스 페티그루의 어느 특별한 하루  

In [6]:
count_vect = CountVectorizer(min_df = 0, ngram_range=(1,2))
genre_mat = count_vect.fit_transform(movies['장르'])
print(genre_mat.shape)

(1999, 241)


In [7]:
from sklearn.metrics.pairwise import cosine_similarity
genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim)

[[1.         1.         0.         ... 0.         0.57735027 0.37796447]
 [1.         1.         0.         ... 0.         0.57735027 0.37796447]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.57735027 0.57735027 0.         ... 0.         1.         0.21821789]
 [0.37796447 0.37796447 0.         ... 0.         0.21821789 1.        ]]


In [8]:
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1]
print(genre_sim_sorted_ind[:1])

[[  0 575 590 ... 691 690 999]]


In [9]:
C = movies['평점'].mean()
m = movies['투표수'].quantile(0.6)

def weighted_vote_average(record):
    v = record['투표수']
    R = record['평점']
    
    return ((v/(v+m))*R) + ((m/(m+v))*C)

movies['투표가중치']=movies.apply(weighted_vote_average, axis=1)

In [10]:
movies[['제목', '평점', '투표수', '투표가중치']].sort_values('투표가중치', ascending = False)[:10]

제목    평점    투표수     투표가중치
0         그린 북  9.61   5937  9.399134
8     보헤미안 랩소디  9.42  39381  9.388674
7       쇼생크 탈출  9.43  17677  9.362769
22  어벤져스: 엔드게임  9.38  68732  9.362711
11         알라딘  9.40  26052  9.354909
25      위대한 쇼맨  9.38  13734  9.301282
16    인생은 아름다워  9.39  12057  9.300453
39       세 얼간이  9.34  25823  9.298333
12         월-E  9.40   9963  9.292947
37        주토피아  9.35  18473  9.292322

In [11]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    
    title_movie=df[df['제목']==title_name]
    title_index=title_movie.index.values
    similar_indexes=sorted_ind[title_index, :(top_n)]
    
    similar_indexes=similar_indexes.reshape(-1)
    similar_index = similar_indexes[similar_indexes!=title_index]
   
    return df.iloc[similar_indexes].sort_values('투표가중치', ascending=False)[:top_n]

In [12]:
f = open("D:/github/beta/be/test.txt" ,"r+", encoding='utf-8')
line = ''

In [16]:
while True:
    f = open("D:/github/beta/be/test.txt" ,"r+", encoding='utf-8')
    while True:
        line = f.readline()
        if line != '':
            print(line)
            similar_movies = find_sim_movie(movies, genre_sim_sorted_ind, line, 10)
            f = open("D:/github/beta/be/result.txt" ,'w', encoding='utf-8')
            sm = similar_movies[['제목','평점']].to_string()
            print(similar_movies[['제목','평점']])
            f.write(sm)
            break
    f.close()
    f = open("D:/github/beta/be/test.txt" ,'w', encoding='utf-8')
    f.write('')
    f.close()

매트릭스
                 제목    평점
17             매트릭스  9.39
89           쥬라기 공원  9.28
572        스타쉽 트루퍼스  8.96
726           토탈 리콜  8.86
964           13 구역  8.71
1978            엑스맨  8.03
1854       인디펜던스 데이  8.11
1946  2009 로스트 메모리즈  8.05
1698      클라우드 아틀라스  8.22
1865  트랜스포머: 패자의 역습  8.11
매트릭스
                 제목    평점
17             매트릭스  9.39
89           쥬라기 공원  9.28
572        스타쉽 트루퍼스  8.96
726           토탈 리콜  8.86
964           13 구역  8.71
1978            엑스맨  8.03
1854       인디펜던스 데이  8.11
1946  2009 로스트 메모리즈  8.05
1698      클라우드 아틀라스  8.22
1865  트랜스포머: 패자의 역습  8.11
알라딘
                 제목    평점
11              알라딘  9.40
60              라푼젤  9.33
146  하이 스쿨 뮤지컬: 졸업반  9.25
387      내 깡패 같은 애인  9.07
390           물랑 루즈  9.07
526       마법에 걸린 사랑  8.99
47              알라딘  9.34
150           인어 공주  9.24
453      당신이 잠든 사이에  9.03
841          미녀와 야수  8.78
알라딘
                 제목    평점
11              알라딘  9.40
60              라푼젤  9.33
146  하이 스쿨 뮤지컬: 졸업반  9.25
387      내 깡패 같은 애인 

KeyboardInterrupt: 